name: KeepInventoryShop
version: 1.5
main: keepinventoryshop.KeepInventoryShop
authors: [oMrSnow]
description: A plugin to purchase Keep Inventory lives
api-version: 1.19
depend: [Vault]
softdepend: [WorldGuard]
commands:
  keepinventory:
    description: Keep Inventory lives management command
    usage: /keepinventory [buy|lives|set|add|remove|upgrade|help|reload]
    aliases: [keepinventory, ki]
permissions:
  keepinventoryshop.set:
    description: Allows the player to set lives for others
    default: op
  keepinventoryshop.add:
    description: Allows the player to add lives for others
    default: op
  keepinventoryshop.remove:
    description: Allows the player to remove lives for others
    default: op
  keepinventoryshop.view.others:
    description: Allows the player to view lives of other players
    default: op
  keepinventoryshop.reload:
    description: Allows the player to reload the Keep Inventory configuration
    default: op
